language: go

go:
  - "1.8"
  - "1.9"
  - "1.10.x"

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - mkdir -p $GOPATH/src/anbillon.com && cd .. && mv gpnm $GOPATH/src/anbillon.com/
  - cd $GOPATH/src/anbillon.com/gpnm

install:
  - dep ensure -v

script:
  - go build